### ISSUE TITLE
insertMany usages allow event & meta undefined

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-ledger-storage-mongodb#54]
Here is the major issue I've found:

`events.add` has to 2 guards in it:

https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/blob/36016ac8c71c55e870d4df8fee84aa9623f960f2/lib/LedgerEventStorage.js#L87-L92

`events.addMany` has no guards in it.

This means that `events.addMany` will write an event that is undefined to mongodb:

https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/blob/876c06b43a58cbbc80d75c68b1eae0f16f26b77f/test/mocha/30-event-api.js#L567-L596

https://github.com/digitalbazaar/bedrock-ledger-storage-mongodb/blob/876c06b43a58cbbc80d75c68b1eae0f16f26b77f/test/mocha/30-event-api.js#L535-L566

Questions:
1. Is this the right layer? (the guards in add suggest so)
    - One small caveat: ledger validators should be catching this before write
2. Should we allow an event where meta is undefined? (again guards in `events.add` suggest no)

Solutions:

`events.addMany` is supposed to be robust or fault tolerant so these suggestions follow that pattern.

1. filter and warn:

```js
// this is used to make chunks
const _events = events.filter.(({event, meta}) => {
    if(!(event && _.isObject(event))) {
      logger.warn('event is required', {event, meta});
      return false;
    }
    if(!(meta && meta.eventHash)) {
      logger.warn('`meta.eventHash` is required.', {event, meta});
      return false;
    }
    return true;
});
```

2. filter and add errors to object

```js
// this is returned along with dupHashes
const errors = [];
// this is used to make chunks
const _events = events.filter(({event. meta}) => {
    if(!(event && _.isObject(event))) {
      errors.push(new TypeError('`event` must be an object.'));
      return false;
    }
    if(!(meta && meta.eventHash)) {
      errors.push(new TypeError('`meta.eventHash` is required.'));
      return false;
    }
    return true;
})
```

3. just throw and stop writing

4. [use a mongodb schema validator](https://docs.mongodb.com/manual/core/schema-validation/)

**Comment by mattcollier** [comment]
First, thank you for bringing this up. At minimum the behavior needs to be documented.  Here are my thoughts:

- On a ledger system at this storage level, one event follows from another and therefore, not writing an event submitted to the API for any reason (other than duplicate) is an error condition.
- As a practical matter, the events submitted to this API are generated by ledger code itself or go through extreme vetting in other parts of the stack.  Validation at this level would be an *additional* integrity check.
- The code paths that include `insertMany` are in the hot path and is considered an *advanced* API. There is a desire to get things written to the database as quickly as possible.
- This is one of those cases where malformed events would likely only be encountered during a development process and would be quickly discovered due to catastrophic failure.  It would be a shame to pay the validation penalty forever.  It brings to mind the idea in `assert-plus` that assertions can be enabled/disabled via an environment/config variable.  https://github.com/joyent/node-assert-plus#assert-plus.  This brings up the possibility of using assert-plus to make assertions about the events. 

@dlongley what are your thoughts on this matter?

**Comment by dlongley** [comment]
@mattcollier -- I agree with all your points. I don't think we want to pay a penalty here.

**Comment by aljones15** [comment]
just to make sure we are clear here on implementation:

1. remove tests for these conditions
2. do not implement any validation checks in the `addMany` routes.

or use `assert-plus`?

**Comment by mattcollier** [comment]
@aljones15 your two points here look correct, I don't think we want to use assert-plus at this time either.

**Comment by aljones15** [comment]
closing as no further changes are required.
